spring:
  application.name: shareit
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    username: "test"
    password: "test"
    url: "jdbc:h2:mem:shareit"
    driver-class-name: "org.h2.Driver"